version: '3.7'

services:
  api:
    container_name: purchase-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - './purchase_api:/usr/src/app'
    networks:
      - fastpay-network
    ports:
      - 5000:5000
    environment:
      - DB_NAME=purchase
      - DB_URL=mongodb://database-purchase:27018/purchase
      - DB_TEST_NAME=purchase_test
      - DB_TEST_URL=mongodb://database-purchase:27018/purchase_test
      - FLASK_APP=application/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=application.config.DevelopmentConfig
      - PRODUCTS_API=http://app:3000/
  
  database-purchase:
    container_name: database-purchase
    image: mongo
    command: mongod --port 27018
    volumes:
      - /mongo_purchase:/data/db
    networks:
      - fastpay-network
    ports:
      - 27018:27018
  
networks:
  fastpay-network:
    name: fastpay-network